services:
  api:
    build:
      context: ./api
    ports:
      - "3333:3333"
    environment:
      - MONGO_URI=mongodb://mongo:27017/meu-banco
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.16
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL="http://api:3333/api"
    depends_on:
      - api

volumes:
  data:
    driver: local

networks:
  network-api:
    driver: bridge
